# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjnToHtYaGMXXraNCt8vL5c5ZB3onNvL
"""

from google.colab import drive
import os

drive.mount('/content/drive', force_remount=True)

# Clean up old data if it exists
!rm -rf /content/dataset/hanabi_dataset

# Unzip with the -qo (quiet, overwrite) flag
# Ensure this path matches exactly where your zip is in Drive
zip_path = "/content/drive/MyDrive/ML_project/hanabi_dataset.zip"
!unzip -qo "{zip_path}" -d "/content/dataset"

print("Unzip complete. Folders found:")
!ls /content/dataset/hanabi_dataset | head -n 5

import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np
from sklearn.utils import class_weight

data_dir = "/content/dataset/hanabi_dataset"
img_height, img_width = 448, 448
batch_size = 4

# Load training data
train_ds = tf.keras.utils.image_dataset_from_directory(
  data_dir, validation_split=0.2, subset="training", seed=123,
  image_size=(img_height, img_width), batch_size=batch_size)

# Load validation data
val_ds = tf.keras.utils.image_dataset_from_directory(
  data_dir, validation_split=0.2, subset="validation", seed=123,
  image_size=(img_height, img_width), batch_size=batch_size)

class_names = train_ds.class_names
print(f"\nRecognizing {len(class_names)} cards: {class_names}")

# Extract labels to calculate weights
y_train = np.concatenate([y for x, y in train_ds], axis=0)
weights = class_weight.compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train)

class_weight_dict = dict(enumerate(weights))
print("Class weights assigned to balance the dataset.")

# 1. Data Augmentation (Artificial variety)
data_augmentation = tf.keras.Sequential([
  layers.RandomFlip("horizontal_and_vertical"),
  layers.RandomRotation(0.2),
  layers.RandomZoom(0.2),
  layers.RandomContrast(0.1)
])

# 2. Base Brain
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(448, 448, 3), include_top=False, weights='imagenet')

# Fine-tuning: Freeze first 100 layers, train the rest
base_model.trainable = True
for layer in base_model.layers[:100]:
    layer.trainable = False

# 3. Final Assembly
model = models.Sequential([
  layers.Input(shape=(448, 448, 3)),
  data_augmentation,
  base_model,
  layers.GlobalAveragePooling2D(),
  layers.Dropout(0.4),
  layers.Dense(len(class_names), activation='softmax')
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

print("Model architecture ready.")

epochs = 30
history = model.fit(
  train_ds,
  validation_data=val_ds,
  epochs=epochs,
  class_weight=class_weight_dict
)